---
title: "Outline"
author: "Emma Grossman"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Overview
Each week I will read through Chapters of R for Data Science by Hadley Wickham & Garret Grolemund and Machine Learning with R by Brett Lantz and complete the exercises provided in the chapters. If time permits, I'll find an external data set and implement the methods I've learned.

## 2. Weekly topics

1. Exploratory Data Analysis (Chapter 5 r4ds) 
2. Lazy Learning - Classification Using Nearest Neighbors (Chapter 3 MLwR)
3. Tibbles with tibble (Chapter 7 r4ds), Data import with readr (Chapter 8 r4ds) \& Probabilistic Learning - Classification Using Naive Bayes (Chapter 4 MLwR)
4. Tidy Data with tidyr (Chapter 9 r4ds), Divide and Conquer - Classification Using Decision Trees and Rules (Chapter 5 MLwR)
5. Relational Data with dplyr (Chapter 10 r4ds), Understanding regression trees and model trees (pps. 200-216) (Chapter 6 MLwR)  \&Black Box Methods - Neural Networks and Support Vector Machines (Chapter 7 MLwR)
6. five interviews in three days (!!) & Finding Patterns - Market Basket Analysis Using Association Rules (Chapter 8 MLwR) (some)
7. Strings with stringr (Chapter 11 r4ds) \& Finding Patterns - Market Basket Analysis Using Association Rules (Chapter 8 MLwR) (finish) 
8. factors with forcats (Chapter 12 r4ds) \& Evaluating Model Performance (Chapter 10 MLwR) 
9. Dates and Times with lubridate (Chapter 13 r4ds) \& Pipes with magrittr (Chapter 14 r4ds) \& Improving Model Performance (Chapter 11 MLwR)
10. https://adv-r.hadley.nz/functions.html \& tidy models: Functions (Chapter 15 r4ds) \& Vectors (Chapter 16 r4ds) \& Specialized Machine Learning Topics (Chapter 12 MLwR)


